### ISSUE TITLE
下载文件报错

### ISSUE THREAD

**Issue by MrQuJL** [kings1990/fast-request#12]
### 当前使用版本(Current Version)
2.0.6
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
下载文件的请求执行成功了，但是文件下载不下来
![jdfw](https://user-images.githubusercontent.com/20641014/139644774-eb52a88c-c78b-49e7-88dc-6b9cfa34dd7e.gif)

### 报错信息(Error Message)
java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 221,4,main]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2168)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1289)
	at com.intellij.openapi.fileChooser.ex.FileSaverDialogImpl.init(FileSaverDialogImpl.java:67)
	at com.intellij.openapi.fileChooser.ex.FileSaverDialogImpl.save(FileSaverDialogImpl.java:104)
	at com.intellij.openapi.fileChooser.ex.FileSaverDialogImpl.save(FileSaverDialogImpl.java:62)
	at com.intellij.openapi.fileChooser.FileSaverDialog.save(FileSaverDialog.java:22)
	at io.github.kings1990.plugin.fastrequest.view.FastRequestToolWindow$2.run(FastRequestToolWindow.java:636)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by kings1990** [comment]
mac seems ok, Will be optimized in 2.0.7

**Comment by kings1990** [comment]
update to 2.0.7
